name: Docker Hub

on:
  push:
    paths-ignore:
      - 'docs/**'

    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
          -
            name: Checkout 
            uses: actions/checkout@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          -
            name: Get current util version
            id: get_version
            run: |
              echo "::set-output name=version::$(/usr/bin/env python3 src/codeplag/brand_consts.py --version)"
          -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: ./Dockerfile
              builder: ${{ steps.buildx.outputs.name }}
              push: true
              tags: |
                ${{ secrets.DOCKER_HUB_USERNAME }}/code-plagiarism-ubuntu18.04:latest
                ${{ secrets.DOCKER_HUB_USERNAME }}/code-plagiarism-ubuntu18.04:${{ steps.get_version.outputs.version }}
              cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/code-plagiarism-ubuntu18.04:buildcache
              cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/code-plagiarism-ubuntu18.04:buildcache,mode=max