#!/usr/bin/env python3

import subprocess
import sys

try:
    completed = subprocess.run(
        ['python3', '-m', 'codeplag'] + sys.argv[1:],
        check=True
    )
except subprocess.CalledProcessError as error:
    sys.exit(error.returncode)
